# Generated by Django 3.1.7 on 2023-12-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'copilot_chat_session',
                'managed': True,
            },
        ),
    ]
