# Generated by Django 4.2.8 on 2023-12-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'managed': False},
        ),
    ]
